server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  charset utf-8;

  location /assets/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /images/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=604800";
  }

  location /models/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=604800";
  }

  location ~* \.glb$ {
    default_type model/gltf-binary;
    try_files $uri =404;
    add_header Cache-Control "public, max-age=604800";
  }

  location ~* \.gltf$ {
    default_type model/gltf+json;
    try_files $uri =404;
    add_header Cache-Control "public, max-age=604800";
  }

  location /scenes/ {
    try_files $uri =404;
    add_header Cache-Control "no-cache";
  }

  location = /cv.pdf {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=604800";
  }

  location = /index.html {
    default_type text/html;
    try_files $uri =404;
    add_header Cache-Control "no-cache";
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache";
  }
}
