export const MAX_SHADOW_LIGHTS = 3;
export const DEFAULT_SHADOW_MAP_SIZE = 512;
export const LITE_SHADOW_MAP_SCALE = 0.75;
export const DEFAULT_SHADOW_REFRESH_INTERVAL = 30;
export const LITE_SHADOW_REFRESH_INTERVAL = 36;
export const DEFAULT_SHADOW_DIRTY_DEBOUNCE = 1;
export const LITE_SHADOW_DIRTY_DEBOUNCE = 2;

export const POINT_LIGHT_CULLING_ENABLED = true;
export const POINT_LIGHT_VIEWER_CULL_DISTANCE = 4;
export const POINT_LIGHT_EDITOR_CULL_DISTANCE = 10;
export const POINT_LIGHT_RUNTIME_CULL_DISTANCE = 4;
export const POINT_LIGHT_CULL_HYSTERESIS = 0;
